((nil . ((cmake-ide-build-dir . "./build/")
         (cmake-ide-cmake-args . (""))
         )
      )
 )
;; ((nil . ((setq helm-ctest-dir "..//build/Tests/"))))
((nil . ((cmake-compile-command . ""))))
((nil . ((cmake-ide-cmake-args . ""))))
((nil . ((cmake-ide-clang-flags-c++ . "-I/usr/local/include -I/usr/include"))))
((nil . ((company-clang-arguments . ("-I/usr/local/include -I/usr/include")))))
